AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Lint/UselessMethodDefinition:
  Enabled: false

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - class_methods
  MethodCreatingMethods:
    - included

Naming/PredicatePrefix:
  AllowedMethods:
    - have_breadcrumb
    - have_breadcrumbs

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false
